-- Run this in Supabase SQL Editor to create the cats table.
create table if not exists public.cats (
  id bigint primary key generated by default as identity,
  name text not null,
  age int not null,
  breed text not null
);

-- Optional: enable RLS and add policy, or leave open for anon key.
-- alter table public.cats enable row level security;
-- create policy "Allow read" on public.cats for select using (true);
